FROM python:3.7.9-stretch

WORKDIR /myflask

COPY order_ms.py /myflask/app.py

RUN pip install flask
RUN pip install flask_restful
RUN pip install pymysql
RUN pip install kafka-python

CMD [ "flask", "run",  "--host", "0.0.0.0", "--port", "5000" ]